version: '3.5'
services:
  openvpn-br0:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: openvpn-br0
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - ETH=eth0
      - ETH_IP_NETMASK="192.168.50.99/24"
      - ETH_BROADCAST="192.168.50.255"
      - ETH_GATEWAY="192.168.50.1"
    network_mode: host
    logging:
      options:
        max-size: 100M